Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd = GetCurrentDir()
src = Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('controls', src,depend = [''],CPPPATH = CPPPATH)

Return('group')
