import os
from building import *

cwd = GetCurrentDir()

# Add source code
src = Glob('*.c')
src += Glob("e-ink/*.c")
src += Glob("elm/*.c")
src += Glob("font/*.c")
src += Glob("GUI/*.c")
#src += Glob("opm060e9_driver/*.c")



path = [cwd + '/GUI']
path += [cwd + '/font']
path += [cwd + '/e-ink']
path += [cwd + '/font']
path += [cwd + '/elm']
#path += [cwd + '/opm060e9_driver']
group = DefineGroup('Applications', src, depend = [''], CPPPATH = path)

Return('group')
