from building import *
import rtconfig
import os

src = ['main.cpp','epub_mem.c']
inc = []
cwd = GetCurrentDir() # get current dir path

# check if files with ext_name exsit
def check_file_exsit(path, ext_name):
	file_dirs = os.listdir(path)
	for file_dir in file_dirs:
		if os.path.splitext(file_dir)[1] in ext_name:
			return True
	return False



inc = inc + [cwd]
for root, dirs, files in os.walk(cwd):
	for dir in dirs:
		current_path = os.path.join(root, dir)

		#Use relative path for C source code, so .o will generated in build subfolder
		current_path2 = current_path.replace(cwd, '')
		current_path2 = current_path2[1:]


		if check_file_exsit(current_path, ['.c', '.cpp']): # add .h and .hpp path
			src = src + Glob(os.path.join(current_path2,'*.c')) # add all .c files
			src = src + Glob(os.path.join(current_path2,'*.cpp')) # add all .cpp files
		
		if check_file_exsit(current_path, ['.h', '.hpp']): # add .h and .hpp path
			inc = inc + [current_path]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc)
Return('group')