from building import *
import rtconfig
import os

src = []
inc = []
cwd = GetCurrentDir() # get current dir path
inc = inc + [cwd]


# check if files with ext_name exsit
def check_file_exsit(path, ext_name):
    file_dirs = os.listdir(path)
    for file_dir in file_dirs:
        if os.path.splitext(file_dir)[1] in ext_name:
            return True
    return False




for root, dirs, files in os.walk(cwd):
    for dir in dirs:
        current_path = os.path.join(root, dir)

        #Use relative path for C source code, so .o will generated in build subfolder
        current_path2 = current_path.replace(cwd, '')
        current_path2 = current_path2[1:]
        
        if current_path2.startswith('epdiy_original'):
            continue

        inc = inc + [current_path]

        if current_path2.startswith('touch') or current_path2.startswith('m5Paper') or current_path2.startswith('sd_card') or current_path2.startswith('spiffs'):
            continue

        if check_file_exsit(current_path, ['.c', '.cpp']): # add .h and .hpp path
            src = src + Glob(os.path.join(current_path2,'*.c')) # add all .c files
            src = src + Glob(os.path.join(current_path2,'*.cpp')) # add all .cpp files




CPPDEFINES =['__EPUB_SF32LB5x__']
group = DefineGroup('Applications', src, depend = [''], CPPPATH = inc, CPPDEFINES = CPPDEFINES)
Return('group')